### ISSUE TITLE
Error when directory exists within configured secrets directory

### ISSUE THREAD

**Issue by rawkode** [GT8Online/weave#31]
```
=INFO REPORT==== 13-Aug-2017::10:08:04 ===
    application: logger
    exited: stopped
    type: temporary
** (Mix) Could not start application thought_service: exited in: ThoughtService.Application.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (File.Error) could not read file "/run/secrets/kubernetes.io": illegal operation on a directory
            (elixir) lib/file.ex:272: File.read!/1
            (weave) lib/loaders/file.ex:40: Weave.Loaders.File.load_configuration/3
            (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2
            (elixir) lib/enum.ex:675: Enum.each/2
            (weave) lib/loaders/file.ex:25: Weave.Loaders.File.load_configuration/0
            (thought_service) lib/thought_service.ex:8: ThoughtService.Application.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
ERROR: Job failed: error executing remote command: command terminated with non-zero exit code: Error executing in Docker Container: 1
```

**Comment by rawkode** [comment]
Closed by #32
